openai_api_key: YOUR_OPENAI_KEY
openai_model: gpt-3.5-turbo
tts_api: https://api.elevenlabs.io/v1/text-to-speech/VOICE_ID
tts_api_key: YOUR_ELEVENLABS_KEY
record_seconds: 5
rate: 16000
hotkey: CommandOrControl+Shift+H
